// New England Golf Courses - 84 Public Courses
export const newEnglandCourses = [
  // ==================== MAINE (11 courses) ====================
  {
    id: 1,
    name: 'Belgrade Lakes Golf Club',
    description: 'Clive Clark designed gem in central Maine with stunning lake views',
    city: 'Belgrade Lakes',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 71,
    price_weekday: 79,
    price_weekend: 99,
    rating: 4.6,
  },
  {
    id: 2,
    name: 'Sugarloaf Golf Club',
    description: 'Robert Trent Jones Jr. mountain masterpiece in ski country',
    city: 'Carrabassett Valley',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 72,
    price_weekday: 89,
    price_weekend: 115,
    rating: 4.7,
  },
  {
    id: 3,
    name: 'Sunday River Golf Club',
    description: 'Robert Trent Jones Jr. design overlooking Sunday River Valley',
    city: 'Newry',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 72,
    price_weekday: 89,
    price_weekend: 119,
    rating: 4.8,
  },
  {
    id: 4,
    name: 'Boothbay Harbor Country Club',
    description: 'Scenic coastal course in charming Boothbay Harbor',
    city: 'Boothbay Harbor',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 71,
    price_weekday: 65,
    price_weekend: 85,
    rating: 4.3,
  },
  {
    id: 5,
    name: 'Fox Ridge Golf Club',
    description: 'Championship layout with excellent conditioning',
    city: 'Auburn',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 72,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.4,
  },
  {
    id: 6,
    name: 'Kebo Valley Golf Club',
    description: 'Historic course near Acadia National Park, 8th oldest in America',
    city: 'Bar Harbor',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 70,
    price_weekday: 75,
    price_weekend: 95,
    rating: 4.5,
  },
  {
    id: 7,
    name: 'The Ledges Golf Club',
    description: 'Challenging layout carved through Maine woods',
    city: 'York',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 72,
    price_weekday: 69,
    price_weekend: 89,
    rating: 4.4,
  },
  {
    id: 8,
    name: 'Brunswick Golf Club',
    description: 'Classic Maine public course with traditional layout',
    city: 'Brunswick',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 72,
    price_weekday: 50,
    price_weekend: 65,
    rating: 4.2,
  },
  {
    id: 9,
    name: 'Links at Outlook',
    description: 'Links-style course with open terrain and ocean breezes',
    city: 'Berwick',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 71,
    price_weekday: 59,
    price_weekend: 79,
    rating: 4.3,
  },
  {
    id: 10,
    name: 'Martindale Country Club',
    description: 'Well-maintained public course with friendly atmosphere',
    city: 'Auburn',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 71,
    price_weekday: 45,
    price_weekend: 55,
    rating: 4.1,
  },
  {
    id: 11,
    name: 'Penobscot Valley Country Club',
    description: 'Donald Ross design with classic New England character',
    city: 'Orono',
    state: 'ME',
    region: 'Maine',
    holes: 18,
    par_total: 72,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.3,
  },

  // ==================== CAPE COD (22 courses) ====================
  {
    id: 12,
    name: 'Cape Cod National Golf Club',
    description: 'Top-rated championship course, best public golf on Cape Cod',
    city: 'Brewster',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 95,
    price_weekend: 125,
    rating: 4.8,
  },
  {
    id: 13,
    name: 'Captains Golf Course - Port',
    description: 'Championship 18-hole layout with strategic bunkering',
    city: 'Brewster',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 75,
    price_weekend: 95,
    rating: 4.6,
  },
  {
    id: 14,
    name: 'Captains Golf Course - Starboard',
    description: 'Sister course to Port with different character and challenge',
    city: 'Brewster',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 75,
    price_weekend: 95,
    rating: 4.5,
  },
  {
    id: 15,
    name: 'Cranberry Valley Golf Course',
    description: 'Premier public championship-style course on Cape Cod',
    city: 'Harwich',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 70,
    price_weekend: 85,
    rating: 4.5,
  },
  {
    id: 16,
    name: 'Dennis Pines Golf Course',
    description: 'Long, tree-lined layout with strategic challenges',
    city: 'East Dennis',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 62,
    price_weekend: 75,
    rating: 4.4,
  },
  {
    id: 17,
    name: 'Dennis Highlands Golf Course',
    description: 'Classic town course with rolling terrain',
    city: 'Dennis',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 71,
    price_weekday: 58,
    price_weekend: 70,
    rating: 4.3,
  },
  {
    id: 18,
    name: 'Bass River Golf Course',
    description: 'Historic Donald Ross-designed layout from 1900',
    city: 'South Yarmouth',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 55,
    price_weekend: 68,
    rating: 4.3,
  },
  {
    id: 19,
    name: 'Bayberry Hills Golf Course',
    description: '27 holes of varied terrain and strategic play',
    city: 'West Yarmouth',
    state: 'MA',
    region: 'Cape Cod',
    holes: 27,
    par_total: 72,
    price_weekday: 60,
    price_weekend: 75,
    rating: 4.4,
  },
  {
    id: 20,
    name: 'Hyannis Golf Course',
    description: 'Solid public course with elevation changes',
    city: 'Hyannis',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 71,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.2,
  },
  {
    id: 21,
    name: 'Olde Barnstable Fairgrounds Golf Course',
    description: 'Popular classic layout on the mid-Cape',
    city: 'Marstons Mills',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 71,
    price_weekday: 52,
    price_weekend: 65,
    rating: 4.3,
  },
  {
    id: 22,
    name: 'Highland Links Golf Course',
    description: 'One of the oldest courses in America, true Scottish-style links with ocean views',
    city: 'North Truro',
    state: 'MA',
    region: 'Cape Cod',
    holes: 9,
    par_total: 35,
    price_weekday: 45,
    price_weekend: 55,
    rating: 4.5,
  },
  {
    id: 23,
    name: 'Chatham Seaside Links',
    description: 'Historic seaside 9-hole with great coastal character',
    city: 'Chatham',
    state: 'MA',
    region: 'Cape Cod',
    holes: 9,
    par_total: 34,
    price_weekday: 35,
    price_weekend: 45,
    rating: 4.2,
  },
  {
    id: 24,
    name: 'Brookside Club',
    description: 'Public 18-hole with club atmosphere',
    city: 'Bourne',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 70,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.1,
  },
  {
    id: 25,
    name: 'Cape Cod Country Club',
    description: 'Classic public layout with variety',
    city: 'East Falmouth',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 71,
    price_weekday: 50,
    price_weekend: 65,
    rating: 4.0,
  },
  {
    id: 26,
    name: 'Blue Rock Golf Course',
    description: 'Well maintained 18-hole with relaxed play',
    city: 'South Yarmouth',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 48,
    price_weekend: 60,
    rating: 4.1,
  },
  {
    id: 27,
    name: 'Paul Harney Golf Course',
    description: 'Public course welcoming all skill levels',
    city: 'East Falmouth',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 59,
    price_weekday: 35,
    price_weekend: 45,
    rating: 3.9,
  },
  {
    id: 28,
    name: 'Holly Ridge Golf Club',
    description: 'Family-friendly public course',
    city: 'Sandwich',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 54,
    price_weekday: 32,
    price_weekend: 40,
    rating: 4.0,
  },
  {
    id: 29,
    name: 'Sandwich Hollows Golf Club',
    description: 'Classic town course with traditional feel',
    city: 'Sandwich',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 71,
    price_weekday: 50,
    price_weekend: 62,
    rating: 4.1,
  },
  {
    id: 30,
    name: 'Harwich Port Golf Club',
    description: 'Convenient 9-hole right near town',
    city: 'Harwich',
    state: 'MA',
    region: 'Cape Cod',
    holes: 9,
    par_total: 34,
    price_weekday: 28,
    price_weekend: 35,
    rating: 3.8,
  },
  {
    id: 31,
    name: 'Twin Brooks Golf Course',
    description: 'Public accessible layout for all levels',
    city: 'Hyannis',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 54,
    price_weekday: 30,
    price_weekend: 38,
    rating: 3.9,
  },
  {
    id: 32,
    name: 'Miacomet Golf Club',
    description: 'Top public island layout on Nantucket',
    city: 'Nantucket',
    state: 'MA',
    region: 'Cape Cod',
    holes: 18,
    par_total: 72,
    price_weekday: 85,
    price_weekend: 110,
    rating: 4.5,
  },
  {
    id: 33,
    name: 'Siasconset Golf Course',
    description: 'Historic 9-hole seaside course on Nantucket',
    city: 'Nantucket',
    state: 'MA',
    region: 'Cape Cod',
    holes: 9,
    par_total: 35,
    price_weekday: 40,
    price_weekend: 50,
    rating: 4.2,
  },

  // ==================== MASSACHUSETTS MAINLAND (17 courses) ====================
  {
    id: 34,
    name: 'Pinehills Golf Club - Jones Course',
    description: 'Rees Jones design through pine forests and wetlands',
    city: 'Plymouth',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 85,
    price_weekend: 110,
    rating: 4.7,
  },
  {
    id: 35,
    name: 'Pinehills Golf Club - Nicklaus Course',
    description: 'Jack Nicklaus design with challenging layout',
    city: 'Plymouth',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 85,
    price_weekend: 110,
    rating: 4.6,
  },
  {
    id: 36,
    name: 'Red Tail Golf Club',
    description: 'Brian Silva design, consistently ranked among MA best',
    city: 'Devens',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 79,
    price_weekend: 99,
    rating: 4.7,
  },
  {
    id: 37,
    name: 'Crumpin-Fox Club',
    description: 'Roger Rulewich design in scenic Berkshire foothills',
    city: 'Bernardston',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 75,
    price_weekend: 95,
    rating: 4.6,
  },
  {
    id: 38,
    name: 'Blackstone National Golf Club',
    description: 'Rees Jones championship layout in Sutton',
    city: 'Sutton',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 79,
    price_weekend: 99,
    rating: 4.5,
  },
  {
    id: 39,
    name: 'Butter Brook Golf Club',
    description: 'Mark Mungeam design with excellent conditioning',
    city: 'Westford',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 70,
    price_weekday: 72,
    price_weekend: 89,
    rating: 4.5,
  },
  {
    id: 40,
    name: 'Granite Links Golf Club',
    description: 'Spectacular Boston skyline views from former quarries',
    city: 'Quincy',
    state: 'MA',
    region: 'Massachusetts',
    holes: 27,
    par_total: 72,
    price_weekday: 85,
    price_weekend: 115,
    rating: 4.6,
  },
  {
    id: 41,
    name: 'Crosswinds Golf Club',
    description: 'Challenging layout south of Boston',
    city: 'Plymouth',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.2,
  },
  {
    id: 42,
    name: 'Farm Neck Golf Club',
    description: 'Beautiful Martha\'s Vineyard course where Presidents play',
    city: 'Oak Bluffs',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 95,
    price_weekend: 125,
    rating: 4.5,
  },
  {
    id: 43,
    name: 'Shining Rock Golf Club',
    description: 'Championship course with rock outcroppings',
    city: 'Northbridge',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 65,
    price_weekend: 85,
    rating: 4.3,
  },
  {
    id: 44,
    name: 'Taconic Golf Club',
    description: 'Classic Berkshires course with mountain views',
    city: 'Williamstown',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 71,
    price_weekday: 60,
    price_weekend: 75,
    rating: 4.4,
  },
  {
    id: 45,
    name: 'Waubeeka Golf Links',
    description: 'Scenic Berkshires layout with challenging terrain',
    city: 'Williamstown',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.3,
  },
  {
    id: 46,
    name: 'Waverly Oaks Golf Club',
    description: 'Brian Silva design with excellent playability',
    city: 'Plymouth',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 65,
    price_weekend: 85,
    rating: 4.4,
  },
  {
    id: 47,
    name: 'Brookside Golf Club',
    description: 'Friendly public course with solid layout',
    city: 'Bourne',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 70,
    price_weekday: 48,
    price_weekend: 60,
    rating: 4.0,
  },
  {
    id: 48,
    name: 'George Wright Golf Course',
    description: 'Historic Donald Ross municipal gem in Boston',
    city: 'Hyde Park',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 70,
    price_weekday: 48,
    price_weekend: 62,
    rating: 4.3,
  },
  {
    id: 49,
    name: 'Foxborough Country Club',
    description: 'Near Gillette Stadium, solid public option',
    city: 'Foxborough',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.1,
  },
  {
    id: 50,
    name: 'Country Club of Halifax',
    description: 'Well-maintained public course south of Boston',
    city: 'Halifax',
    state: 'MA',
    region: 'Massachusetts',
    holes: 18,
    par_total: 72,
    price_weekday: 52,
    price_weekend: 65,
    rating: 4.2,
  },

  // ==================== NEW HAMPSHIRE (9 courses) ====================
  {
    id: 51,
    name: 'Mount Washington Golf Course',
    description: 'Historic Donald Ross design at Bretton Woods, NH\'s top public course',
    city: 'Bretton Woods',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 71,
    price_weekday: 99,
    price_weekend: 135,
    rating: 4.7,
  },
  {
    id: 52,
    name: 'Atkinson Resort Golf Course',
    description: 'Championship layout with excellent facilities',
    city: 'Atkinson',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 72,
    price_weekday: 75,
    price_weekend: 95,
    rating: 4.4,
  },
  {
    id: 53,
    name: 'Hidden Valley Championship Golf Course',
    description: 'Challenging mountain course with scenic views',
    city: 'Derry',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 72,
    price_weekday: 55,
    price_weekend: 70,
    rating: 4.2,
  },
  {
    id: 54,
    name: 'Maplewood Golf Course',
    description: 'Donald Ross design in the White Mountains',
    city: 'Bethlehem',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 72,
    price_weekday: 49,
    price_weekend: 65,
    rating: 4.3,
  },
  {
    id: 55,
    name: 'Montcalm Golf Club',
    description: 'Challenging layout with beautiful New Hampshire scenery',
    city: 'Enfield',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 72,
    price_weekday: 52,
    price_weekend: 68,
    rating: 4.3,
  },
  {
    id: 56,
    name: 'Oak Hill Golf Course',
    description: 'Lakes Region course with water views',
    city: 'Meredith',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 71,
    price_weekday: 48,
    price_weekend: 60,
    rating: 4.1,
  },
  {
    id: 57,
    name: 'Waukewan Golf Club',
    description: 'Scenic course in the Lakes Region',
    city: 'Center Harbor',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 71,
    price_weekday: 45,
    price_weekend: 58,
    rating: 4.0,
  },
  {
    id: 58,
    name: 'Breakfast Hill Golf Club',
    description: 'Popular public course with excellent conditioning',
    city: 'Greenland',
    state: 'NH',
    region: 'New Hampshire',
    holes: 18,
    par_total: 71,
    price_weekday: 65,
    price_weekend: 82,
    rating: 4.4,
  },
  {
    id: 59,
    name: 'Hampton Hills Golf Club',
    description: 'Seacoast area course with ocean breezes',
    city: 'Hampton',
    state: 'NH',
    region: 'New Hampshire',
    holes: 9,
    par_total: 35,
    price_weekday: 28,
    price_weekend: 35,
    rating: 3.9,
  },

  // ==================== VERMONT (6 courses) ====================
  {
    id: 60,
    name: 'Jay Peak Resort Golf Course',
    description: 'Mountain resort golf with stunning views near Canadian border',
    city: 'Jay',
    state: 'VT',
    region: 'Vermont',
    holes: 18,
    par_total: 72,
    price_weekday: 69,
    price_weekend: 89,
    rating: 4.4,
  },
  {
    id: 61,
    name: 'Fox Run Golf Club',
    description: 'Excellent public course in southern Vermont',
    city: 'Ludlow',
    state: 'VT',
    region: 'Vermont',
    holes: 9,
    par_total: 35,
    price_weekday: 35,
    price_weekend: 45,
    rating: 4.3,
  },
  {
    id: 62,
    name: 'Green Mountain National Golf Course',
    description: 'Gene Bates championship design in Killington',
    city: 'Killington',
    state: 'VT',
    region: 'Vermont',
    holes: 18,
    par_total: 71,
    price_weekday: 85,
    price_weekend: 110,
    rating: 4.7,
  },
  {
    id: 63,
    name: 'Woodstock Country Club',
    description: 'Robert Trent Jones Sr. design, oldest public course in Vermont',
    city: 'Woodstock',
    state: 'VT',
    region: 'Vermont',
    holes: 18,
    par_total: 70,
    price_weekday: 79,
    price_weekend: 99,
    rating: 4.5,
  },
  {
    id: 64,
    name: 'Links at Lang Farm',
    description: 'Burlington area course with fun layout',
    city: 'Essex',
    state: 'VT',
    region: 'Vermont',
    holes: 18,
    par_total: 72,
    price_weekday: 45,
    price_weekend: 58,
    rating: 4.1,
  },
  {
    id: 65,
    name: 'Killington Golf Course',
    description: 'First municipal course in Vermont with mountain views',
    city: 'Killington',
    state: 'VT',
    region: 'Vermont',
    holes: 18,
    par_total: 72,
    price_weekday: 79,
    price_weekend: 99,
    rating: 4.5,
  },

  // ==================== CONNECTICUT (12 courses) ====================
  {
    id: 66,
    name: 'Wintonbury Hills Golf Course',
    description: 'Pete Dye design, one of Connecticut\'s finest public courses',
    city: 'Bloomfield',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 70,
    price_weekday: 70,
    price_weekend: 90,
    rating: 4.6,
  },
  {
    id: 67,
    name: 'Great River Golf Club',
    description: 'Tommy Fazio design with excellent conditioning',
    city: 'Milford',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 72,
    price_weekday: 95,
    price_weekend: 125,
    rating: 4.5,
  },
  {
    id: 68,
    name: 'Connecticut National Golf Club',
    description: 'Championship layout in the Quiet Corner',
    city: 'Putnam',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 72,
    price_weekday: 59,
    price_weekend: 75,
    rating: 4.3,
  },
  {
    id: 69,
    name: 'Oxford Greens Golf Club',
    description: 'Mark Mungeam design with varied terrain',
    city: 'Oxford',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 72,
    price_weekday: 65,
    price_weekend: 85,
    rating: 4.4,
  },
  {
    id: 70,
    name: 'Fox Hopyard Golf Club',
    description: 'Roger Rulewich design with excellent playability',
    city: 'East Haddam',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 71,
    price_weekday: 69,
    price_weekend: 89,
    rating: 4.5,
  },
  {
    id: 71,
    name: 'Keney Park Golf Course',
    description: 'Historic Hartford municipal with Donald Ross roots',
    city: 'Hartford',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 70,
    price_weekday: 28,
    price_weekend: 35,
    rating: 4.0,
  },
  {
    id: 72,
    name: 'Shennecossett Golf Course',
    description: 'Donald Ross municipal near the shoreline',
    city: 'Groton',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 71,
    price_weekday: 42,
    price_weekend: 55,
    rating: 4.2,
  },
  {
    id: 73,
    name: 'Gillette Ridge Golf Club',
    description: 'Championship course with challenging layout',
    city: 'Bloomfield',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 72,
    price_weekday: 59,
    price_weekend: 75,
    rating: 4.3,
  },
  {
    id: 74,
    name: 'Tashua Knolls Golf Club',
    description: 'Well-maintained public course with club feel',
    city: 'Trumbull',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 72,
    price_weekday: 48,
    price_weekend: 62,
    rating: 4.1,
  },
  {
    id: 75,
    name: 'Richter Park Golf Course',
    description: 'Municipal gem consistently ranked among CT\'s best',
    city: 'Danbury',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 72,
    price_weekday: 52,
    price_weekend: 68,
    rating: 4.4,
  },
  {
    id: 76,
    name: 'Lyman Orchards Golf Club - Player Course',
    description: 'Gary Player design with orchard views',
    city: 'Middlefield',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 71,
    price_weekday: 59,
    price_weekend: 75,
    rating: 4.3,
  },
  {
    id: 77,
    name: 'Lyman Orchards Golf Club - Jones Course',
    description: 'Robert Trent Jones design through orchards',
    city: 'Middlefield',
    state: 'CT',
    region: 'Connecticut',
    holes: 18,
    par_total: 72,
    price_weekday: 59,
    price_weekend: 75,
    rating: 4.4,
  },

  // ==================== RHODE ISLAND (7 courses) ====================
  {
    id: 78,
    name: 'Newport National Golf Club',
    description: 'Rhode Island\'s top public course with fescue-lined links and ocean views',
    city: 'Middletown',
    state: 'RI',
    region: 'Rhode Island',
    holes: 18,
    par_total: 72,
    price_weekday: 89,
    price_weekend: 115,
    rating: 4.6,
  },
  {
    id: 79,
    name: 'Triggs Memorial Golf Course',
    description: 'Classic Donald Ross municipal, consistently ranked among RI\'s best',
    city: 'Providence',
    state: 'RI',
    region: 'Rhode Island',
    holes: 18,
    par_total: 72,
    price_weekday: 52,
    price_weekend: 62,
    rating: 4.3,
  },
  {
    id: 80,
    name: 'Meadow Brook Golf Course',
    description: 'Championship-style public course with large greens',
    city: 'Richmond',
    state: 'RI',
    region: 'Rhode Island',
    holes: 18,
    par_total: 72,
    price_weekday: 48,
    price_weekend: 60,
    rating: 4.2,
  },
  {
    id: 81,
    name: 'North Kingstown Golf Course',
    description: 'Well-reviewed 18-hole municipal layout',
    city: 'North Kingstown',
    state: 'RI',
    region: 'Rhode Island',
    holes: 18,
    par_total: 70,
    price_weekday: 42,
    price_weekend: 52,
    rating: 4.0,
  },
  {
    id: 82,
    name: 'Melody Hill Golf Course',
    description: 'Classic public 18 with good conditioning',
    city: 'Chepachet',
    state: 'RI',
    region: 'Rhode Island',
    holes: 18,
    par_total: 71,
    price_weekday: 40,
    price_weekend: 50,
    rating: 4.0,
  },
  {
    id: 83,
    name: 'Rolling Greens Golf Course',
    description: 'Public 18-hole with fun routing',
    city: 'North Kingstown',
    state: 'RI',
    region: 'Rhode Island',
    holes: 18,
    par_total: 72,
    price_weekday: 38,
    price_weekend: 48,
    rating: 3.9,
  },
  {
    id: 84,
    name: 'East Greenwich Golf Club',
    description: '9-hole with easy public access and great reviews',
    city: 'East Greenwich',
    state: 'RI',
    region: 'Rhode Island',
    holes: 9,
    par_total: 35,
    price_weekday: 25,
    price_weekend: 32,
    rating: 4.0,
  },
];

// New England Lodging Options
export const newEnglandLodging = [
  // ==================== MAINE ====================
  // Hotels & Resorts
  { id: 1, name: 'Sunday River Resort', city: 'Newry', state: 'ME', type: 'Resort', price_per_night: 179, region: 'Maine', sleeps: 4 },
  { id: 2, name: 'Sugarloaf Mountain Hotel', city: 'Carrabassett Valley', state: 'ME', type: 'Resort', price_per_night: 169, region: 'Maine', sleeps: 4 },
  { id: 3, name: 'Bar Harbor Inn', city: 'Bar Harbor', state: 'ME', type: 'Inn', price_per_night: 219, region: 'Maine', sleeps: 2 },
  { id: 4, name: 'Belgrade Lakes Lodge', city: 'Belgrade Lakes', state: 'ME', type: 'Hotel', price_per_night: 159, region: 'Maine', sleeps: 4 },
  // Vacation Rentals
  { id: 101, name: 'Sunday River Ski House', city: 'Newry', state: 'ME', type: 'Vacation Rental', price_per_night: 650, region: 'Maine', sleeps: 14 },
  { id: 102, name: 'Lakefront Lodge on Great Pond', city: 'Belgrade Lakes', state: 'ME', type: 'Vacation Rental', price_per_night: 550, region: 'Maine', sleeps: 12 },
  { id: 103, name: 'Mountain View Retreat', city: 'Bethel', state: 'ME', type: 'Vacation Rental', price_per_night: 475, region: 'Maine', sleeps: 10 },

  // ==================== CAPE COD ====================
  // Hotels & Resorts
  { id: 5, name: 'Ocean Edge Resort', city: 'Brewster', state: 'MA', type: 'Resort', price_per_night: 249, region: 'Cape Cod', sleeps: 4 },
  { id: 6, name: 'Chatham Bars Inn', city: 'Chatham', state: 'MA', type: 'Inn', price_per_night: 399, region: 'Cape Cod', sleeps: 2 },
  { id: 7, name: 'Cape Codder Resort', city: 'Hyannis', state: 'MA', type: 'Resort', price_per_night: 189, region: 'Cape Cod', sleeps: 4 },
  { id: 8, name: 'Seadar Inn', city: 'Harwich Port', state: 'MA', type: 'Inn', price_per_night: 179, region: 'Cape Cod', sleeps: 2 },
  // Vacation Rentals
  { id: 104, name: 'Oceanfront Estate - Chatham', city: 'Chatham', state: 'MA', type: 'Vacation Rental', price_per_night: 1200, region: 'Cape Cod', sleeps: 16 },
  { id: 105, name: 'Harwich Golf House', city: 'Harwich', state: 'MA', type: 'Vacation Rental', price_per_night: 750, region: 'Cape Cod', sleeps: 12 },
  { id: 106, name: 'Dennis Beach Compound', city: 'Dennis', state: 'MA', type: 'Vacation Rental', price_per_night: 850, region: 'Cape Cod', sleeps: 14 },
  { id: 107, name: 'Brewster Captain\'s House', city: 'Brewster', state: 'MA', type: 'Vacation Rental', price_per_night: 600, region: 'Cape Cod', sleeps: 10 },

  // ==================== MASSACHUSETTS ====================
  // Hotels & Resorts
  { id: 10, name: 'Pinehills Resort', city: 'Plymouth', state: 'MA', type: 'Resort', price_per_night: 199, region: 'Massachusetts', sleeps: 4 },
  { id: 11, name: 'Red Lion Inn', city: 'Stockbridge', state: 'MA', type: 'Inn', price_per_night: 229, region: 'Massachusetts', sleeps: 2 },
  { id: 12, name: 'Harbor Hotel', city: 'Provincetown', state: 'MA', type: 'Hotel', price_per_night: 269, region: 'Massachusetts', sleeps: 2 },
  // Vacation Rentals
  { id: 108, name: 'Plymouth Lakehouse', city: 'Plymouth', state: 'MA', type: 'Vacation Rental', price_per_night: 550, region: 'Massachusetts', sleeps: 12 },
  { id: 109, name: 'Berkshires Mountain Estate', city: 'Lenox', state: 'MA', type: 'Vacation Rental', price_per_night: 800, region: 'Massachusetts', sleeps: 16 },

  // ==================== NEW HAMPSHIRE ====================
  // Hotels & Resorts
  { id: 13, name: 'Omni Mount Washington Resort', city: 'Bretton Woods', state: 'NH', type: 'Resort', price_per_night: 329, region: 'New Hampshire', sleeps: 4 },
  { id: 14, name: 'Mountain View Grand', city: 'Whitefield', state: 'NH', type: 'Resort', price_per_night: 249, region: 'New Hampshire', sleeps: 4 },
  { id: 15, name: 'Meredith Bay Resort', city: 'Meredith', state: 'NH', type: 'Resort', price_per_night: 179, region: 'New Hampshire', sleeps: 4 },
  // Vacation Rentals
  { id: 110, name: 'White Mountains Chalet', city: 'Lincoln', state: 'NH', type: 'Vacation Rental', price_per_night: 600, region: 'New Hampshire', sleeps: 14 },
  { id: 111, name: 'Lakes Region Lake House', city: 'Meredith', state: 'NH', type: 'Vacation Rental', price_per_night: 700, region: 'New Hampshire', sleeps: 16 },
  { id: 112, name: 'Ski Country Lodge', city: 'Franconia', state: 'NH', type: 'Vacation Rental', price_per_night: 500, region: 'New Hampshire', sleeps: 12 },

  // ==================== VERMONT ====================
  // Hotels & Resorts
  { id: 16, name: 'Woodstock Inn & Resort', city: 'Woodstock', state: 'VT', type: 'Resort', price_per_night: 299, region: 'Vermont', sleeps: 4 },
  { id: 17, name: 'Killington Grand Resort', city: 'Killington', state: 'VT', type: 'Resort', price_per_night: 189, region: 'Vermont', sleeps: 4 },
  { id: 18, name: 'Jay Peak Resort', city: 'Jay', state: 'VT', type: 'Resort', price_per_night: 159, region: 'Vermont', sleeps: 4 },
  { id: 19, name: 'Stowe Mountain Lodge', city: 'Stowe', state: 'VT', type: 'Resort', price_per_night: 349, region: 'Vermont', sleeps: 4 },
  // Vacation Rentals
  { id: 113, name: 'Killington Ski Lodge', city: 'Killington', state: 'VT', type: 'Vacation Rental', price_per_night: 650, region: 'Vermont', sleeps: 16 },
  { id: 114, name: 'Stowe Mountainside Estate', city: 'Stowe', state: 'VT', type: 'Vacation Rental', price_per_night: 850, region: 'Vermont', sleeps: 14 },
  { id: 115, name: 'Manchester Village House', city: 'Manchester', state: 'VT', type: 'Vacation Rental', price_per_night: 550, region: 'Vermont', sleeps: 12 },
  { id: 116, name: 'Jay Peak Trailside Cabin', city: 'Jay', state: 'VT', type: 'Vacation Rental', price_per_night: 475, region: 'Vermont', sleeps: 10 },

  // ==================== CONNECTICUT ====================
  // Hotels & Resorts
  { id: 20, name: 'Saybrook Point Resort', city: 'Old Saybrook', state: 'CT', type: 'Resort', price_per_night: 279, region: 'Connecticut', sleeps: 4 },
  { id: 21, name: 'Foxwoods Resort', city: 'Mashantucket', state: 'CT', type: 'Resort', price_per_night: 199, region: 'Connecticut', sleeps: 4 },
  { id: 22, name: 'Interlaken Inn', city: 'Lakeville', state: 'CT', type: 'Inn', price_per_night: 189, region: 'Connecticut', sleeps: 2 },
  // Vacation Rentals
  { id: 117, name: 'Mystic Waterfront Estate', city: 'Mystic', state: 'CT', type: 'Vacation Rental', price_per_night: 700, region: 'Connecticut', sleeps: 14 },
  { id: 118, name: 'Litchfield Hills Farmhouse', city: 'Litchfield', state: 'CT', type: 'Vacation Rental', price_per_night: 550, region: 'Connecticut', sleeps: 12 },

  // ==================== RHODE ISLAND ====================
  // Hotels & Resorts
  { id: 23, name: 'Castle Hill Inn', city: 'Newport', state: 'RI', type: 'Inn', price_per_night: 499, region: 'Rhode Island', sleeps: 2 },
  { id: 24, name: 'Newport Marriott', city: 'Newport', state: 'RI', type: 'Hotel', price_per_night: 229, region: 'Rhode Island', sleeps: 4 },
  { id: 25, name: 'Weekapaug Inn', city: 'Westerly', state: 'RI', type: 'Inn', price_per_night: 399, region: 'Rhode Island', sleeps: 2 },
  // Vacation Rentals
  { id: 119, name: 'Newport Mansion Rental', city: 'Newport', state: 'RI', type: 'Vacation Rental', price_per_night: 1100, region: 'Rhode Island', sleeps: 16 },
  { id: 120, name: 'Narragansett Beach House', city: 'Narragansett', state: 'RI', type: 'Vacation Rental', price_per_night: 650, region: 'Rhode Island', sleeps: 12 },
];

// Generate mock tee times for a given date
export function generateMockTeeTimes(courseId, date) {
  const teeTimes = [];
  const course = newEnglandCourses.find(c => c.id === parseInt(courseId));
  if (!course) return [];

  for (let hour = 6; hour < 18; hour++) {
    for (let minute = 0; minute < 60; minute += 12) {
      teeTimes.push({
        id: parseInt(`${courseId}${hour}${minute}`),
        course_id: courseId,
        tee_date: date,
        tee_time: `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}:00`,
        available_slots: Math.floor(Math.random() * 4) + 1,
        course_name: course.name,
        price_weekday: course.price_weekday,
        price_weekend: course.price_weekend,
      });
    }
  }
  return teeTimes;
}

// Generate itinerary based on courses and dates
export function generateItinerary(courses, startDate, numDays) {
  const days = [];

  for (let i = 0; i < numDays; i++) {
    const isGolfDay = i === 1 || i === 3 || i === 5;
    const courseIndex = Math.floor((i / 2)) % courses.length;

    if (i === 0) {
      days.push({
        day: `Day 1 - Arrival`,
        activity: 'Arrive and check into lodging. Explore the area, grab dinner, and rest up for golf tomorrow.',
      });
    } else if (isGolfDay && courses[courseIndex]) {
      days.push({
        day: `Day ${i + 1} - Golf`,
        activity: `Morning round at ${courses[courseIndex].name}. Afternoon free for exploring, beer, or relaxing.`,
      });
    } else if (i === numDays - 1) {
      days.push({
        day: `Day ${i + 1} - Departure`,
        activity: 'Check out and head home. Safe travels!',
      });
    } else {
      days.push({
        day: `Day ${i + 1} - Rest Day`,
        activity: 'Free day to explore local attractions, hike, visit breweries, or hit the range.',
      });
    }
  }

  return days;
}

// Mock bookings storage
let mockBookings = [];
let bookingIdCounter = 1;

export const mockBookingsApi = {
  getAll: () => mockBookings,
  create: (teeTime, players, user) => {
    const isWeekend = new Date(teeTime.tee_date).getDay() % 6 === 0;
    const price = isWeekend ? teeTime.price_weekend : teeTime.price_weekday;
    const booking = {
      id: bookingIdCounter++,
      user_id: user?.id || 1,
      tee_time_id: teeTime.id,
      players,
      total_price: price * players,
      status: 'confirmed',
      tee_date: teeTime.tee_date,
      tee_time: teeTime.tee_time,
      course_name: teeTime.course_name,
      created_at: new Date().toISOString(),
    };
    mockBookings.push(booking);
    return booking;
  },
  cancel: (id) => {
    const booking = mockBookings.find(b => b.id === id);
    if (booking) {
      booking.status = 'cancelled';
    }
    return booking;
  },
};

export const mockUser = {
  id: 1,
  email: 'demo@example.com',
  first_name: 'Demo',
  last_name: 'User',
};

// Legacy export
export const mockCourses = newEnglandCourses;
